POST http://localhost:8080/api/v1/users/oauth/token
Content-Type: application/x-www-form-urlencoded

username=user&password=password&client_id=oauth2-client&grant_type=password

###

GET http://localhost:8080/api/v1/articles/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsicmVzb3VyY2Utc2VydmVyLXJlc3QtYXBpIl0sInVzZXJfbmFtZSI6InVzZXIiLCJzY29wZSI6WyJyZWFkIl0sImV4cCI6MTU4MTM2NTExNSwiYXV0aG9yaXRpZXMiOlsiVVNFUiJdLCJqdGkiOiI0NGQ5YmM2My03ZWU1LTRlZjgtYjMzYy1kZmZiMmU1N2Q2ZjkiLCJjbGllbnRfaWQiOiJvYXV0aDItY2xpZW50In0.JCiR9QivG5dJLlXuGgLVcC0qtkaWNd5xijTl9GpbzPBakwIFFus6cm46jrSwhOfPPDkhG5nYAj-WsKv_eidO7CLlBtWEneDCZbhWNGuGpmu_mqJha64ok1L0Fscp-gpst8UPd0toE9W2DV-t25C8aJwXbYbY4KiyRwzzhc3eMmblEGS16bseksOv9Q5F47bkM3SorE8RTFYTyTAv4-lAuaJAJrwOL8shVx2yzYaQUCllZeHEjPjeSxLNrBLknqE_o0cD0P2N_uJ9O9tL2vjdX14cY9KxofZo1oYmGrrFdGjONe1-7bF5jnQRmY-1jR47N4GnX2pC8O9VtePoFnNEUQ

###

POST localhost:8080/api/v1/articles/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsicmVzb3VyY2Utc2VydmVyLXJlc3QtYXBpIl0sInVzZXJfbmFtZSI6InVzZXIiLCJzY29wZSI6WyJyZWFkIl0sImV4cCI6MTU4MTM2NTExNSwiYXV0aG9yaXRpZXMiOlsiVVNFUiJdLCJqdGkiOiI0NGQ5YmM2My03ZWU1LTRlZjgtYjMzYy1kZmZiMmU1N2Q2ZjkiLCJjbGllbnRfaWQiOiJvYXV0aDItY2xpZW50In0.JCiR9QivG5dJLlXuGgLVcC0qtkaWNd5xijTl9GpbzPBakwIFFus6cm46jrSwhOfPPDkhG5nYAj-WsKv_eidO7CLlBtWEneDCZbhWNGuGpmu_mqJha64ok1L0Fscp-gpst8UPd0toE9W2DV-t25C8aJwXbYbY4KiyRwzzhc3eMmblEGS16bseksOv9Q5F47bkM3SorE8RTFYTyTAv4-lAuaJAJrwOL8shVx2yzYaQUCllZeHEjPjeSxLNrBLknqE_o0cD0P2N_uJ9O9tL2vjdX14cY9KxofZo1oYmGrrFdGjONe1-7bF5jnQRmY-1jR47N4GnX2pC8O9VtePoFnNEUQ

{
  "url": "https://ieeexplore.ieee.org/abstract/document/7436659"
}

###

POST localhost:8080/api/v1/ratings/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsicmVzb3VyY2Utc2VydmVyLXJlc3QtYXBpIl0sInVzZXJfbmFtZSI6InVzZXIiLCJzY29wZSI6WyJyZWFkIl0sImV4cCI6MTU4MTM2NTExNSwiYXV0aG9yaXRpZXMiOlsiVVNFUiJdLCJqdGkiOiI0NGQ5YmM2My03ZWU1LTRlZjgtYjMzYy1kZmZiMmU1N2Q2ZjkiLCJjbGllbnRfaWQiOiJvYXV0aDItY2xpZW50In0.JCiR9QivG5dJLlXuGgLVcC0qtkaWNd5xijTl9GpbzPBakwIFFus6cm46jrSwhOfPPDkhG5nYAj-WsKv_eidO7CLlBtWEneDCZbhWNGuGpmu_mqJha64ok1L0Fscp-gpst8UPd0toE9W2DV-t25C8aJwXbYbY4KiyRwzzhc3eMmblEGS16bseksOv9Q5F47bkM3SorE8RTFYTyTAv4-lAuaJAJrwOL8shVx2yzYaQUCllZeHEjPjeSxLNrBLknqE_o0cD0P2N_uJ9O9tL2vjdX14cY9KxofZo1oYmGrrFdGjONe1-7bF5jnQRmY-1jR47N4GnX2pC8O9VtePoFnNEUQ

{
  "objectivityRating": 7,
  "completionRating": 7,
  "userId": 4,
  "articleId": 1
}

###

GET localhost:8080/api/v1/ratings/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsicmVzb3VyY2Utc2VydmVyLXJlc3QtYXBpIl0sInVzZXJfbmFtZSI6InVzZXIiLCJzY29wZSI6WyJyZWFkIl0sImV4cCI6MTU4MTM2NTExNSwiYXV0aG9yaXRpZXMiOlsiVVNFUiJdLCJqdGkiOiI0NGQ5YmM2My03ZWU1LTRlZjgtYjMzYy1kZmZiMmU1N2Q2ZjkiLCJjbGllbnRfaWQiOiJvYXV0aDItY2xpZW50In0.JCiR9QivG5dJLlXuGgLVcC0qtkaWNd5xijTl9GpbzPBakwIFFus6cm46jrSwhOfPPDkhG5nYAj-WsKv_eidO7CLlBtWEneDCZbhWNGuGpmu_mqJha64ok1L0Fscp-gpst8UPd0toE9W2DV-t25C8aJwXbYbY4KiyRwzzhc3eMmblEGS16bseksOv9Q5F47bkM3SorE8RTFYTyTAv4-lAuaJAJrwOL8shVx2yzYaQUCllZeHEjPjeSxLNrBLknqE_o0cD0P2N_uJ9O9tL2vjdX14cY9KxofZo1oYmGrrFdGjONe1-7bF5jnQRmY-1jR47N4GnX2pC8O9VtePoFnNEUQ

###

GET localhost:8080/api/v1/accumulated-ratings/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsicmVzb3VyY2Utc2VydmVyLXJlc3QtYXBpIl0sInVzZXJfbmFtZSI6InVzZXIiLCJzY29wZSI6WyJyZWFkIl0sImV4cCI6MTU4MTM2NTExNSwiYXV0aG9yaXRpZXMiOlsiVVNFUiJdLCJqdGkiOiI0NGQ5YmM2My03ZWU1LTRlZjgtYjMzYy1kZmZiMmU1N2Q2ZjkiLCJjbGllbnRfaWQiOiJvYXV0aDItY2xpZW50In0.JCiR9QivG5dJLlXuGgLVcC0qtkaWNd5xijTl9GpbzPBakwIFFus6cm46jrSwhOfPPDkhG5nYAj-WsKv_eidO7CLlBtWEneDCZbhWNGuGpmu_mqJha64ok1L0Fscp-gpst8UPd0toE9W2DV-t25C8aJwXbYbY4KiyRwzzhc3eMmblEGS16bseksOv9Q5F47bkM3SorE8RTFYTyTAv4-lAuaJAJrwOL8shVx2yzYaQUCllZeHEjPjeSxLNrBLknqE_o0cD0P2N_uJ9O9tL2vjdX14cY9KxofZo1oYmGrrFdGjONe1-7bF5jnQRmY-1jR47N4GnX2pC8O9VtePoFnNEUQ

###
