POST http://localhost:8080/api/v1/users/register
Content-Type: application/json

{
  "accountNonExpired": true,
  "accountNonLocked": true,
  "credentialsNonExpired": true,
  "enabled": true,
  "username": "testuser123",
  "password": "$2a$08$BO53tsxv2nE3qhJ2o/4ehet9yM6.KwTXgVR17yvhjooXXahTDCBFu",
  "roles": [
    {
      "id": 3
    }
  ]
}

###

POST http://localhost:8080/api/v1/users/oauth/token
Content-Type: application/x-www-form-urlencoded

username=testuser123&password=password&grant_type=password

###

GET http://3.121.125.69/api/v1/articles/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsicmVzb3VyY2Utc2VydmVyLXJlc3QtYXBpIl0sInVzZXJfbmFtZSI6InVzZXIiLCJzY29wZSI6WyJyZWFkIl0sImV4cCI6MTU5NTk3MzIzMSwiYXV0aG9yaXRpZXMiOlsiVVNFUiJdLCJqdGkiOiJhNzY5NTI1MC1jYTdmLTRjYTEtYWUyMy03ZjFmZDdhYzhhY2IiLCJjbGllbnRfaWQiOiJvYXV0aDItY2xpZW50In0.kBv3E5C5hql9BrCo6-E_TOJ1lwuXHm-xJWKH1UQdsg-mZM1Z2tDsSg2_DtJP5ccZYtoUZizS2zmj3Mu_kPUfXbMqat4ZAw3xjQblRdP1qZSZMZRgS6yrvhHSirP_SeypfirYm4kLJ44arvjjmsPCKjTf2957XhOgCBJ6T-tVAFOcIwOqPO8KUyIwPX4oJA0QAoXkgB4G-GQRmJOmj9lhgKVnErIBUWhc0tTAm4cqwp4ABwJ7_3LP9EfamoSqHzpOdV5w5ejrCKucvPlMlWSBgAq23iwhA53SUy9bhJvixV2nMwjSGira9FwS-2-8rcrFcM-8VHSWMFnsA1trEVN2mQ

###

POST http://3.121.125.69/api/v1/articles/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsicmVzb3VyY2Utc2VydmVyLXJlc3QtYXBpIl0sInVzZXJfbmFtZSI6InVzZXIiLCJzY29wZSI6WyJyZWFkIl0sImV4cCI6MTU5NTk3MzIzMSwiYXV0aG9yaXRpZXMiOlsiVVNFUiJdLCJqdGkiOiJhNzY5NTI1MC1jYTdmLTRjYTEtYWUyMy03ZjFmZDdhYzhhY2IiLCJjbGllbnRfaWQiOiJvYXV0aDItY2xpZW50In0.kBv3E5C5hql9BrCo6-E_TOJ1lwuXHm-xJWKH1UQdsg-mZM1Z2tDsSg2_DtJP5ccZYtoUZizS2zmj3Mu_kPUfXbMqat4ZAw3xjQblRdP1qZSZMZRgS6yrvhHSirP_SeypfirYm4kLJ44arvjjmsPCKjTf2957XhOgCBJ6T-tVAFOcIwOqPO8KUyIwPX4oJA0QAoXkgB4G-GQRmJOmj9lhgKVnErIBUWhc0tTAm4cqwp4ABwJ7_3LP9EfamoSqHzpOdV5w5ejrCKucvPlMlWSBgAq23iwhA53SUy9bhJvixV2nMwjSGira9FwS-2-8rcrFcM-8VHSWMFnsA1trEVN2mQ

{
  "url": "https://ieeexplore.ieee.org/abstract/document/7436659"
}

###

POST http://3.121.125.69/api/v1/ratings/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsicmVzb3VyY2Utc2VydmVyLXJlc3QtYXBpIl0sInVzZXJfbmFtZSI6InVzZXIiLCJzY29wZSI6WyJyZWFkIl0sImV4cCI6MTU5NTk3MzIzMSwiYXV0aG9yaXRpZXMiOlsiVVNFUiJdLCJqdGkiOiJhNzY5NTI1MC1jYTdmLTRjYTEtYWUyMy03ZjFmZDdhYzhhY2IiLCJjbGllbnRfaWQiOiJvYXV0aDItY2xpZW50In0.kBv3E5C5hql9BrCo6-E_TOJ1lwuXHm-xJWKH1UQdsg-mZM1Z2tDsSg2_DtJP5ccZYtoUZizS2zmj3Mu_kPUfXbMqat4ZAw3xjQblRdP1qZSZMZRgS6yrvhHSirP_SeypfirYm4kLJ44arvjjmsPCKjTf2957XhOgCBJ6T-tVAFOcIwOqPO8KUyIwPX4oJA0QAoXkgB4G-GQRmJOmj9lhgKVnErIBUWhc0tTAm4cqwp4ABwJ7_3LP9EfamoSqHzpOdV5w5ejrCKucvPlMlWSBgAq23iwhA53SUy9bhJvixV2nMwjSGira9FwS-2-8rcrFcM-8VHSWMFnsA1trEVN2mQ

{
  "objectivityRating": 3,
  "completionRating": 3,
  "userId": 4,
  "articleId": 1
}

###

GET http://3.121.125.69/api/v1/ratings/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsicmVzb3VyY2Utc2VydmVyLXJlc3QtYXBpIl0sInVzZXJfbmFtZSI6InVzZXIiLCJzY29wZSI6WyJyZWFkIl0sImV4cCI6MTU5NTk3MzIzMSwiYXV0aG9yaXRpZXMiOlsiVVNFUiJdLCJqdGkiOiJhNzY5NTI1MC1jYTdmLTRjYTEtYWUyMy03ZjFmZDdhYzhhY2IiLCJjbGllbnRfaWQiOiJvYXV0aDItY2xpZW50In0.kBv3E5C5hql9BrCo6-E_TOJ1lwuXHm-xJWKH1UQdsg-mZM1Z2tDsSg2_DtJP5ccZYtoUZizS2zmj3Mu_kPUfXbMqat4ZAw3xjQblRdP1qZSZMZRgS6yrvhHSirP_SeypfirYm4kLJ44arvjjmsPCKjTf2957XhOgCBJ6T-tVAFOcIwOqPO8KUyIwPX4oJA0QAoXkgB4G-GQRmJOmj9lhgKVnErIBUWhc0tTAm4cqwp4ABwJ7_3LP9EfamoSqHzpOdV5w5ejrCKucvPlMlWSBgAq23iwhA53SUy9bhJvixV2nMwjSGira9FwS-2-8rcrFcM-8VHSWMFnsA1trEVN2mQ

###

GET http://3.121.125.69/api/v1/accumulated-ratings/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsicmVzb3VyY2Utc2VydmVyLXJlc3QtYXBpIl0sInVzZXJfbmFtZSI6InVzZXIiLCJzY29wZSI6WyJyZWFkIl0sImV4cCI6MTU5NTk3MzIzMSwiYXV0aG9yaXRpZXMiOlsiVVNFUiJdLCJqdGkiOiJhNzY5NTI1MC1jYTdmLTRjYTEtYWUyMy03ZjFmZDdhYzhhY2IiLCJjbGllbnRfaWQiOiJvYXV0aDItY2xpZW50In0.kBv3E5C5hql9BrCo6-E_TOJ1lwuXHm-xJWKH1UQdsg-mZM1Z2tDsSg2_DtJP5ccZYtoUZizS2zmj3Mu_kPUfXbMqat4ZAw3xjQblRdP1qZSZMZRgS6yrvhHSirP_SeypfirYm4kLJ44arvjjmsPCKjTf2957XhOgCBJ6T-tVAFOcIwOqPO8KUyIwPX4oJA0QAoXkgB4G-GQRmJOmj9lhgKVnErIBUWhc0tTAm4cqwp4ABwJ7_3LP9EfamoSqHzpOdV5w5ejrCKucvPlMlWSBgAq23iwhA53SUy9bhJvixV2nMwjSGira9FwS-2-8rcrFcM-8VHSWMFnsA1trEVN2mQ

###
